# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_bar_code',
            field=models.CharField(max_length=64, verbose_name='商品编码'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_detail',
            field=models.TextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_img',
            field=models.CharField(max_length=128, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_market_price',
            field=models.FloatField(default=0, verbose_name='超市价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_name',
            field=models.CharField(max_length=64, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_price',
            field=models.FloatField(default=0, verbose_name='商品单价'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_store_num',
            field=models.IntegerField(default=10, verbose_name='商品数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.GoodsTypeTwo', verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_unit',
            field=models.CharField(max_length=32, verbose_name='称重类型'),
        ),
        migrations.AlterField(
            model_name='goodstypeone',
            name='g_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='商品种类'),
        ),
        migrations.AlterField(
            model_name='goodstypetwo',
            name='g_name',
            field=models.CharField(max_length=32, verbose_name='商品类型'),
        ),
        migrations.AlterField(
            model_name='goodstypetwo',
            name='g_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodstypetwos', to='FruitServer.GoodsTypeOne', verbose_name='种类编号'),
        ),
    ]
