# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-19 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruituser',
            name='f_email',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_phone',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='fruituser',
            name='f_username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
