# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-22 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FruitServer', '0002_auto_20191022_1856'),
        ('Fruits', '0002_auto_20191019_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_goods_num', models.IntegerField(default=1, verbose_name='数量')),
                ('is_select', models.BooleanField(default=True, verbose_name='是否选中')),
                ('c_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.Goods')),
                ('c_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruits.FruitUser')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=64)),
                ('g_price', models.FloatField(default=0)),
                ('g_market_price', models.FloatField(default=0)),
                ('g_unit', models.CharField(max_length=32)),
                ('g_detail', models.TextField()),
                ('g_img', models.CharField(max_length=128)),
                ('g_bar_code', models.CharField(max_length=64)),
                ('g_store_num', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_status', models.IntegerField(default='0')),
                ('o_price', models.FloatField(default=0)),
                ('o_order_time', models.DateTimeField(auto_now_add=True)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruits.FruitUser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField(default=1)),
                ('o_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fruits.Order')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='g_ordergoods',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Fruits.OrderGoods'),
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FruitServer.GoodsTypeTwo'),
        ),
    ]
