# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0004_auto_20191023_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_select',
            field=models.BooleanField(default=True),
        ),
    ]
